In [3]:
import numpy as np
import pandas as pd

In [4]:
friendships = np.array([(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4),(4, 5), (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)])
friendships

array([[0, 1],
       [0, 2],
       [1, 2],
       [1, 3],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6],
       [5, 7],
       [6, 8],
       [7, 8],
       [8, 9]])

In [5]:
print(friendships[:,0])
print(friendships[:,1])

[0 0 1 1 2 3 4 5 5 6 7 8]
[1 2 2 3 3 4 5 6 7 8 8 9]


In [6]:
y_actu = pd.Series(friendships[:,0])
y_pred = pd.Series(friendships[:,1])
df_confusion = pd.crosstab(y_actu, y_pred, rownames=['Actual'], colnames=['Predicted'], margins=True)

In [7]:
df_confusion

Predicted  1  2  3  4  5  6  7  8  9  All
Actual                                   
0          1  1  0  0  0  0  0  0  0    2
1          0  1  1  0  0  0  0  0  0    2
2          0  0  1  0  0  0  0  0  0    1
3          0  0  0  1  0  0  0  0  0    1
4          0  0  0  0  1  0  0  0  0    1
5          0  0  0  0  0  1  1  0  0    2
6          0  0  0  0  0  0  0  1  0    1
7          0  0  0  0  0  0  0  1  0    1
8          0  0  0  0  0  0  0  0  1    1
All        1  2  2  1  1  1  1  2  1   12

In [12]:
confusion=np.array(df_confusion)
confusion[:-1,:-1]

array([[1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [8]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements 

In [13]:
accuracy(confusion[:-1,:-1])

0.6666666666666666

### pd.Series(np.diag(df), index=[df.index, df.columns]) this can also trace out the diagonal